name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Debug Structure
      run: ls -R

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker Image
      working-directory: project-1
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-app .

    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/devops-app

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/devops-app
          sudo docker stop devops-app || true
          sudo docker rm devops-app || true
          sudo docker run -d -p 80:80 --name devops-app ${{ secrets.DOCKER_USERNAME }}/devops-app
