name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

    - name: Build Docker Image
      run: docker build -t $DOCKER_USERNAME/devops-app .

    - name: Push Docker Image
      run: docker push $DOCKER_USERNAME/devops-app

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          sudo docker pull awais-devops/devops-app
          sudo docker stop devops-app || true
          sudo docker rm devops-app || true
          sudo docker run -d -p 80:80 --name devops-app YOUR_DOCKER_USERNAME/devops-app
